### ISSUE TITLE
Launch error on Mac OS

### ISSUE THREAD

**Issue by yipukangda** [jupyterlab/jupyterlab_app#147]
Hi,

I tried to launch the app but faulted with a error massage below:
```
[I 16:06:44.464 LabApp] JupyterLab beta preview extension loaded from /Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 16:06:44.464 LabApp] JupyterLab application directory is /Users/jgs/anaconda3/share/jupyter/lab
[W 16:06:44.467 LabApp] Error loading server extension jupyterlab
Traceback (most recent call last):
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 321, in __init__
self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1165, in _run
proc = Process(cmd, **kwargs)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 73, in __init__
self.proc = self._create_process(cwd=cwd, env=env)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 131, in _create_process
cmd[0] = which(cmd[0], kwargs.get('env'))
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/jlpmapp.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1454, in init_server_extensions
func(self)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/extension.py", line 111, in load_jupyter_server_extension
info = get_app_info(app_dir)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 244, in get_app_info
handler = _AppHandler(app_dir, logger)
File "/Users/jgs/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 324, in __init__
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 16:06:44.476 LabApp] Serving notebooks from local directory: /Users/jgs
[I 16:06:44.476 LabApp] 0 active kernels
[I 16:06:44.476 LabApp] The Jupyter Notebook is running at:
[I 16:06:44.476 LabApp] http://localhost:8888/?token=50e69b8dcfd39d15b454f10f133ac8954b22e892f4a93ff4
[I 16:06:44.476 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:06:44.479 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=50e69b8dcfd39d15b454f10f133ac8954b22e892f4a93ff4
[I 16:06:44.968 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 16:06:45.012 LabApp] 404 GET /lab?token=61a5332503ebc005b855d7694e485885527ab7d0880d9e04 (::1) 44.68ms referer=None
```
Does it mean I need to install `nodejs` first?

Thanks

**Comment by declanvk** [comment]
This looks similar to https://github.com/jupyterlab/jupyterlab/issues/3984.

Would you mind letting me know what version of jupyterlab/jupyter you are running?

**Comment by yipukangda** [comment]
Hi @declanvk

The version of jupyterlab/jupyter is 0.31.4 and 5.4.0, respectively.

**Comment by declanvk** [comment]
@yipukangda Glad everything works now!
